from __future__ import annotations

import csv
import json
import subprocess
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class SlimBridgeConfig:
    genome_length: int = 1_000_000
    population_size: int = 1_000
    generations: int = 50
    payload_copy_count: int = 16
    mutation_rate: float = 1.0e-8
    recombination_rate: float = 1.0e-8
    selection_coefficient: float = 0.0
    dominance: float = 0.5
    seed: int = 17
    tree_seq_output: str | None = None


@dataclass(frozen=True)
class SlimRunResult:
    script_path: Path
    stdout_path: Path
    stderr_path: Path
    csv_path: Path
    summary_path: Path
    report_path: Path
    returncode: int


def render_slim_script(config: SlimBridgeConfig) -> str:
    """Render a neutral/selected marker-tracking SLiM script.

    The script tracks payload marker inheritance at the population level. The
    byte-level payload mutation/authentication analysis remains in Python; this
    bridge is for future cross-checks of allele survival under Wright-Fisher
    population dynamics.
    """

    tree_seq_initialize = "    initializeTreeSeq();\n" if config.tree_seq_output else ""
    tree_seq_output = (
        f'    sim.treeSeqOutput("{_escape_eidos_string(config.tree_seq_output)}");\n'
        if config.tree_seq_output
        else ""
    )

    return f"""// Auto-generated by genome_survival_sim.slim_backend
// Purpose: population-level payload marker survival bridge.
// Run with: slim this_file.slim

initialize() {{
    setSeed({config.seed});
    initializeSLiMModelType("WF");
{tree_seq_initialize.rstrip()}
    initializeMutationRate({config.mutation_rate:.12g});
    initializeMutationType("mPayload", {config.dominance:.6g}, "f", {config.selection_coefficient:.12g});
    initializeGenomicElementType("g1", mPayload, 1.0);
    initializeGenomicElement(g1, 0, {config.genome_length - 1});
    initializeRecombinationRate({config.recombination_rate:.12g});
}}

1 early() {{
    sim.addSubpop("p1", {config.population_size});
}}

1 late() {{
    genomes = p1.genomes;
    n = min(c({config.payload_copy_count}, size(genomes)));
    chosen = sample(genomes, n);
    for (g in chosen) {{
        pos = asInteger(runif(1, 0, {config.genome_length - 1}));
        g.addNewDrawnMutation(mPayload, pos);
    }}
    catn("generation,carrier_genomes,total_payload_markers,marker_frequency");
}}

1:{config.generations} late() {{
    carrierGenomes = sum(p1.genomes.countOfMutationsOfType(mPayload) > 0);
    totalMarkers = size(sim.mutationsOfType(mPayload));
    markerFrequency = sum(sim.mutationFrequencies(p1, sim.mutationsOfType(mPayload)));
    catn(sim.generation + "," + carrierGenomes + "," + totalMarkers + "," + markerFrequency);
}}

{config.generations} late() {{
{tree_seq_output.rstrip()}
    sim.simulationFinished();
}}
"""


def write_slim_script(config: SlimBridgeConfig, path: str | Path) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_slim_script(config), encoding="utf-8")


def _escape_eidos_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def parse_slim_stdout(text: str, population_size: int | None = None) -> list[dict[str, object]]:
    """Parse the CSV-like stdout emitted by the generated SLiM bridge script."""

    header: list[str] | None = None
    rows: list[dict[str, object]] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line == "generation,carrier_genomes,total_payload_markers,marker_frequency":
            header = line.split(",")
            continue
        if header is None:
            continue
        parts = line.split(",")
        if len(parts) != len(header):
            continue
        try:
            row: dict[str, object] = {
                "generation": int(parts[0]),
                "carrier_genomes": int(parts[1]),
                "total_payload_markers": int(parts[2]),
                "marker_frequency_sum": float(parts[3]),
            }
        except ValueError:
            continue
        if population_size is not None and population_size > 0:
            row["carrier_genome_rate"] = int(parts[1]) / (2 * population_size)
        rows.append(row)
    return rows


def summarize_slim_rows(rows: list[dict[str, object]], population_size: int | None = None) -> dict[str, object]:
    if not rows:
        return {
            "generations_observed": 0,
            "population_size": population_size,
            "final_generation": None,
            "final_carrier_genomes": 0,
            "final_carrier_genome_rate": 0.0,
            "final_total_payload_markers": 0,
            "final_marker_frequency_sum": 0.0,
            "marker_loss_generation": None,
        }

    final = rows[-1]
    marker_loss_generation = None
    for row in rows:
        if int(row["carrier_genomes"]) == 0 or int(row["total_payload_markers"]) == 0:
            marker_loss_generation = int(row["generation"])
            break

    final_rate = final.get("carrier_genome_rate")
    if final_rate is None and population_size:
        final_rate = int(final["carrier_genomes"]) / (2 * population_size)

    return {
        "generations_observed": len(rows),
        "population_size": population_size,
        "final_generation": final["generation"],
        "final_carrier_genomes": final["carrier_genomes"],
        "final_carrier_genome_rate": final_rate if final_rate is not None else None,
        "final_total_payload_markers": final["total_payload_markers"],
        "final_marker_frequency_sum": final["marker_frequency_sum"],
        "marker_loss_generation": marker_loss_generation,
    }


def make_slim_report(summary: dict[str, object], rows: list[dict[str, object]]) -> str:
    lines = [
        "# SLiM Marker Survival Report",
        "",
        f"- Observed generations: `{summary['generations_observed']}`",
        f"- Final generation: `{summary['final_generation']}`",
        f"- Final carrier genomes: `{summary['final_carrier_genomes']}`",
        f"- Final carrier genome rate: `{summary['final_carrier_genome_rate']}`",
        f"- Final payload marker count: `{summary['final_total_payload_markers']}`",
        f"- Final marker frequency sum: `{summary['final_marker_frequency_sum']}`",
        f"- Marker loss generation: `{summary['marker_loss_generation']}`",
        "",
        "## Interpretation",
        "",
        "- This report tracks population-level payload marker survival in SLiM.",
        "- It does not replace the Python payload decoder, which still evaluates block/auth/payload integrity.",
        "- Use this as a cross-check for drift and selection effects before integrating tskit/pyslim tree sequences.",
        "",
    ]

    if rows:
        lines.extend(
            [
                "## Last Rows",
                "",
                "| generation | carrier_genomes | carrier_genome_rate | total_payload_markers | marker_frequency_sum |",
                "|---:|---:|---:|---:|---:|",
            ]
        )
        for row in rows[-10:]:
            lines.append(
                "| "
                f"{row['generation']} | "
                f"{row['carrier_genomes']} | "
                f"{row.get('carrier_genome_rate', 'NA')} | "
                f"{row['total_payload_markers']} | "
                f"{row['marker_frequency_sum']} |"
            )
    return "\n".join(lines)


def write_slim_analysis(
    rows: list[dict[str, object]],
    out_dir: str | Path,
    population_size: int | None = None,
) -> tuple[Path, Path, Path]:
    target = Path(out_dir)
    target.mkdir(parents=True, exist_ok=True)
    csv_path = target / "slim_marker_metrics.csv"
    summary_path = target / "slim_summary.json"
    report_path = target / "slim_report.md"

    fieldnames = [
        "generation",
        "carrier_genomes",
        "carrier_genome_rate",
        "total_payload_markers",
        "marker_frequency_sum",
    ]
    with csv_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in fieldnames})

    summary = summarize_slim_rows(rows, population_size=population_size)
    with summary_path.open("w", encoding="utf-8") as handle:
        json.dump(summary, handle, ensure_ascii=False, indent=2)
    report_path.write_text(make_slim_report(summary, rows), encoding="utf-8")
    return csv_path, summary_path, report_path


def run_slim_script(
    script_path: str | Path,
    out_dir: str | Path,
    slim_bin: str = "slim",
    population_size: int | None = None,
    timeout_seconds: int | None = None,
) -> SlimRunResult:
    script = Path(script_path)
    target = Path(out_dir)
    target.mkdir(parents=True, exist_ok=True)
    stdout_path = target / "slim_stdout.txt"
    stderr_path = target / "slim_stderr.txt"

    completed = subprocess.run(
        [slim_bin, script.name],
        check=False,
        capture_output=True,
        text=True,
        cwd=script.parent if script.parent != Path("") else None,
        timeout=timeout_seconds,
    )
    stdout_path.write_text(completed.stdout, encoding="utf-8")
    stderr_path.write_text(completed.stderr, encoding="utf-8")
    if completed.returncode != 0:
        raise RuntimeError(
            f"SLiM exited with code {completed.returncode}. "
            f"See {stderr_path} for stderr and {stdout_path} for stdout."
        )

    rows = parse_slim_stdout(completed.stdout, population_size=population_size)
    csv_path, summary_path, report_path = write_slim_analysis(rows, target, population_size=population_size)
    return SlimRunResult(
        script_path=script,
        stdout_path=stdout_path,
        stderr_path=stderr_path,
        csv_path=csv_path,
        summary_path=summary_path,
        report_path=report_path,
        returncode=completed.returncode,
    )


def parse_slim_stdout_file(
    stdout_path: str | Path,
    out_dir: str | Path,
    population_size: int | None = None,
) -> tuple[Path, Path, Path]:
    text = Path(stdout_path).read_text(encoding="utf-8")
    rows = parse_slim_stdout(text, population_size=population_size)
    return write_slim_analysis(rows, out_dir, population_size=population_size)
